"""initial schema

Revision ID: ed1fc2a55f8d
Revises:
Create Date: 2026-08-09 15:07:15.368273

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "ed1fc2a55f8d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_config",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_app_config")),
    )
    op.create_index(op.f("ix_app_config_key"), "app_config", ["key"], unique=True)
    op.create_table(
        "castes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("religion", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_castes")),
        sa.UniqueConstraint("religion", "name", name="uq_caste_religion_name"),
    )
    op.create_index(op.f("ix_castes_religion"), "castes", ["religion"], unique=False)
    op.create_table(
        "conversations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("last_message_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversations")),
    )
    op.create_index(op.f("ix_conversations_last_message_at"), "conversations", ["last_message_at"], unique=False)
    op.create_table(
        "countries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=2), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_countries")),
        sa.UniqueConstraint("name", name=op.f("uq_countries_name")),
    )
    op.create_index(op.f("ix_countries_code"), "countries", ["code"], unique=True)
    op.create_table(
        "education_levels",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_education_levels")),
    )
    op.create_index(op.f("ix_education_levels_name"), "education_levels", ["name"], unique=True)
    op.create_table(
        "interests",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("slug", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_interests")),
    )
    op.create_index(op.f("ix_interests_slug"), "interests", ["slug"], unique=True)
    op.create_table(
        "languages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_languages")),
    )
    op.create_index(op.f("ix_languages_code"), "languages", ["code"], unique=True)
    op.create_table(
        "occupations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_occupations")),
    )
    op.create_index(op.f("ix_occupations_name"), "occupations", ["name"], unique=True)
    op.create_table(
        "religions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_religions")),
    )
    op.create_index(op.f("ix_religions_name"), "religions", ["name"], unique=True)
    op.create_table(
        "states",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("country_code", sa.String(length=2), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_states")),
        sa.UniqueConstraint("country_code", "name", name="uq_state_country_name"),
    )
    op.create_index(op.f("ix_states_country_code"), "states", ["country_code"], unique=False)
    op.create_table(
        "subscription_plans",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("duration_days", sa.Integer(), nullable=False),
        sa.Column("features", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscription_plans")),
    )
    op.create_index(op.f("ix_subscription_plans_is_active"), "subscription_plans", ["is_active"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("phone_number", sa.String(length=20), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("phone_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("email_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "account_status",
            sa.Enum(
                "PENDING",
                "ACTIVE",
                "SUSPENDED",
                "BANNED",
                "DELETED",
                name="accountstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "role",
            sa.Enum(
                "USER", "MODERATOR", "VERIFIER", "ADMIN", "SUPER_ADMIN", name="userrole", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("is_banned", sa.Boolean(), nullable=False),
        sa.Column("banned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_active_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
        sa.UniqueConstraint("phone_number", name=op.f("uq_users_phone_number")),
    )
    op.create_index(op.f("ix_users_account_status"), "users", ["account_status"], unique=False)
    op.create_index("ix_users_active", "users", ["account_status", "deleted_at"], unique=False)
    op.create_index(op.f("ix_users_deleted_at"), "users", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_users_last_active_at"), "users", ["last_active_at"], unique=False)
    op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)
    op.create_table(
        "astrology_profiles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("time_of_birth", sa.DateTime(timezone=True), nullable=True),
        sa.Column("place_of_birth", sa.String(), nullable=True),
        sa.Column("birth_lat", sa.Float(), nullable=True),
        sa.Column("birth_lng", sa.Float(), nullable=True),
        sa.Column("birth_timezone", sa.String(), nullable=True),
        sa.Column(
            "rashi",
            sa.Enum(
                "MESHA",
                "VRISHABHA",
                "MITHUNA",
                "KARKA",
                "SIMHA",
                "KANYA",
                "TULA",
                "VRISHCHIKA",
                "DHANU",
                "MAKARA",
                "KUMBHA",
                "MEENA",
                name="astrologyrashi",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column(
            "nakshatra",
            sa.Enum(
                "ASHWINI",
                "BHARANI",
                "KRITTIKA",
                "ROHINI",
                "MRIGASHIRA",
                "ARDRA",
                "PUNARVASU",
                "PUSHYA",
                "ASHLESHA",
                "MAGHA",
                "PURVA_PHALGUNI",
                "UTTARA_PHALGUNI",
                "HASTA",
                "CHITRA",
                "SWATI",
                "VISHAKHA",
                "ANURADHA",
                "JYESHTHA",
                "MOOLA",
                "PURVA_ASHADHA",
                "UTTARA_ASHADHA",
                "SHRAVANA",
                "DHANISHTA",
                "SHATABHISHA",
                "PURVA_BHADRAPADA",
                "UTTARA_BHADRAPADA",
                "REVATI",
                name="nakshatra",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("gothram", sa.String(), nullable=True),
        sa.Column(
            "dosham",
            sa.Enum("NONE", "MANGAL", "PARTHIV", "OTHER", name="dosham", native_enum=False, length=32),
            nullable=True,
        ),
        sa.Column("horoscope_data", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=True),
        sa.Column("horoscope_verified", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "birth_lat IS NULL OR (birth_lat BETWEEN -90 AND 90)", name=op.f("ck_astrology_profiles_birth_lat_range")
        ),
        sa.CheckConstraint(
            "birth_lng IS NULL OR (birth_lng BETWEEN -180 AND 180)", name=op.f("ck_astrology_profiles_birth_lng_range")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_astrology_profiles_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_astrology_profiles")),
    )
    op.create_index(op.f("ix_astrology_profiles_rashi"), "astrology_profiles", ["rashi"], unique=False)
    op.create_index(op.f("ix_astrology_profiles_user_id"), "astrology_profiles", ["user_id"], unique=True)
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("entity_type", sa.String(length=100), nullable=True),
        sa.Column("entity_id", sa.String(length=100), nullable=True),
        sa.Column("metadata", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=512), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"], ["users.id"], name=op.f("fk_audit_logs_actor_user_id_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index("ix_audit_actor_created", "audit_logs", ["actor_user_id", "created_at"], unique=False)
    op.create_index(op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False)
    op.create_index(op.f("ix_audit_logs_created_at"), "audit_logs", ["created_at"], unique=False)
    op.create_index(op.f("ix_audit_logs_entity_id"), "audit_logs", ["entity_id"], unique=False)
    op.create_index(op.f("ix_audit_logs_entity_type"), "audit_logs", ["entity_type"], unique=False)
    op.create_table(
        "blocks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("blocker_id", sa.Uuid(), nullable=False),
        sa.Column("blocked_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["blocked_id"], ["users.id"], name=op.f("fk_blocks_blocked_id_users"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["blocker_id"], ["users.id"], name=op.f("fk_blocks_blocker_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_blocks")),
        sa.UniqueConstraint("blocker_id", "blocked_id", name="uq_block_pair"),
    )
    op.create_index(op.f("ix_blocks_blocked_id"), "blocks", ["blocked_id"], unique=False)
    op.create_index(op.f("ix_blocks_blocker_id"), "blocks", ["blocker_id"], unique=False)
    op.create_table(
        "conversation_participants",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_conversation_participants_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_conversation_participants_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversation_participants")),
        sa.UniqueConstraint("conversation_id", "user_id", name="uq_conversation_user"),
    )
    op.create_index(
        op.f("ix_conversation_participants_conversation_id"),
        "conversation_participants",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conversation_participants_user_id"), "conversation_participants", ["user_id"], unique=False
    )
    op.create_table(
        "families",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "family_type",
            sa.Enum("JOINT", "NUCLEAR", "EXTENDED", name="familytype", native_enum=False, length=32),
            nullable=True,
        ),
        sa.Column(
            "family_values",
            sa.Enum(
                "TRADITIONAL", "MODERATE", "LIBERAL", "ORTHODOX", name="familyvalues", native_enum=False, length=32
            ),
            nullable=True,
        ),
        sa.Column("about_family", sa.String(length=2000), nullable=True),
        sa.Column("family_location", sa.String(length=150), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_families_user_id_users"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_families")),
    )
    op.create_index(op.f("ix_families_user_id"), "families", ["user_id"], unique=True)
    op.create_table(
        "family_members",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("relationship", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("occupation", sa.String(length=100), nullable=True),
        sa.Column("education", sa.String(length=100), nullable=True),
        sa.Column(
            "marital_status",
            sa.Enum(
                "NEVER_MARRIED",
                "DIVORCED",
                "WIDOWED",
                "AWAITING_DIVORCE",
                name="maritalstatus",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_family_members_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_family_members")),
        sa.UniqueConstraint("user_id", "relationship", name="uq_family_member_role"),
    )
    op.create_index(op.f("ix_family_members_user_id"), "family_members", ["user_id"], unique=False)
    op.create_table(
        "matches",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user1_id", sa.Uuid(), nullable=False),
        sa.Column("user2_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "UNMATCHED", "BLOCKED", "EXPIRED", name="matchstatus", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("matched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("unmatched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("user1_id < user2_id", name=op.f("ck_matches_ck_match_normalized_order")),
        sa.ForeignKeyConstraint(
            ["user1_id"], ["users.id"], name=op.f("fk_matches_user1_id_users"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user2_id"], ["users.id"], name=op.f("fk_matches_user2_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_matches")),
        sa.UniqueConstraint("user1_id", "user2_id", name="uq_match_pair"),
    )
    op.create_index(op.f("ix_matches_status"), "matches", ["status"], unique=False)
    op.create_index(op.f("ix_matches_user1_id"), "matches", ["user1_id"], unique=False)
    op.create_index(op.f("ix_matches_user2_id"), "matches", ["user2_id"], unique=False)
    op.create_index("ix_matches_user2_status", "matches", ["user2_id", "status"], unique=False)
    op.create_index("ix_matches_user_status", "matches", ["user1_id", "status"], unique=False)
    op.create_table(
        "messages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("sender_id", sa.Uuid(), nullable=False),
        sa.Column(
            "message_type",
            sa.Enum("TEXT", "IMAGE", "SYSTEM", name="messagetype", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("body", sa.String(length=5000), nullable=True),
        sa.Column("media_url", sa.String(length=1000), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_messages_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["sender_id"], ["users.id"], name=op.f("fk_messages_sender_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
    )
    op.create_index("ix_messages_conversation_created", "messages", ["conversation_id", "created_at"], unique=False)
    op.create_index(op.f("ix_messages_conversation_id"), "messages", ["conversation_id"], unique=False)
    op.create_index(op.f("ix_messages_deleted_at"), "messages", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_messages_sender_id"), "messages", ["sender_id"], unique=False)
    op.create_table(
        "notifications",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("body", sa.String(length=2000), nullable=True),
        sa.Column("data", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=True),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_notifications_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    op.create_index(op.f("ix_notifications_created_at"), "notifications", ["created_at"], unique=False)
    op.create_index(op.f("ix_notifications_is_read"), "notifications", ["is_read"], unique=False)
    op.create_index(op.f("ix_notifications_type"), "notifications", ["type"], unique=False)
    op.create_index(op.f("ix_notifications_user_id"), "notifications", ["user_id"], unique=False)
    op.create_index("ix_notifications_user_read", "notifications", ["user_id", "is_read"], unique=False)
    op.create_table(
        "partner_preferences",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("age_min", sa.Integer(), nullable=True),
        sa.Column("age_max", sa.Integer(), nullable=True),
        sa.Column("height_min_cm", sa.Integer(), nullable=True),
        sa.Column("height_max_cm", sa.Integer(), nullable=True),
        sa.Column("preferred_marital_status", sa.String(), nullable=True),
        sa.Column("preferred_physical_status", sa.String(), nullable=True),
        sa.Column("preferred_family_values", sa.String(), nullable=True),
        sa.Column("preferred_education", sa.String(), nullable=True),
        sa.Column("preferred_employed_in", sa.String(), nullable=True),
        sa.Column(
            "religion_level",
            sa.Enum("REQUIRED", "PREFERRED", "NO_PREFERENCE", name="preferencelevel", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column(
            "caste_level",
            sa.Enum("REQUIRED", "PREFERRED", "NO_PREFERENCE", name="preferencelevel", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column(
            "language_level",
            sa.Enum("REQUIRED", "PREFERRED", "NO_PREFERENCE", name="preferencelevel", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column(
            "country_level",
            sa.Enum("REQUIRED", "PREFERRED", "NO_PREFERENCE", name="preferencelevel", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column(
            "state_level",
            sa.Enum("REQUIRED", "PREFERRED", "NO_PREFERENCE", name="preferencelevel", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column(
            "diet_level",
            sa.Enum("REQUIRED", "PREFERRED", "NO_PREFERENCE", name="preferencelevel", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "age_min IS NULL OR age_max IS NULL OR age_min <= age_max", name=op.f("ck_partner_preferences_age_range")
        ),
        sa.CheckConstraint(
            "height_min_cm IS NULL OR height_max_cm IS NULL OR height_min_cm <= height_max_cm",
            name=op.f("ck_partner_preferences_height_range"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_partner_preferences_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_partner_preferences")),
    )
    op.create_index("ix_partner_preferences_user", "partner_preferences", ["user_id"], unique=False)
    op.create_index(op.f("ix_partner_preferences_user_id"), "partner_preferences", ["user_id"], unique=True)
    op.create_table(
        "payments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "payment_type",
            sa.Enum("SUBSCRIPTION", "JOB_VERIFICATION", "OTHER", name="paymenttype", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "SUCCESS",
                "FAILED",
                "REFUNDED",
                "CANCELLED",
                name="paymentstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("provider_payment_id", sa.String(length=255), nullable=True),
        sa.Column("metadata", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=True),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_payments_user_id_users"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payments")),
    )
    op.create_index(op.f("ix_payments_provider_payment_id"), "payments", ["provider_payment_id"], unique=True)
    op.create_index(op.f("ix_payments_status"), "payments", ["status"], unique=False)
    op.create_index(op.f("ix_payments_user_id"), "payments", ["user_id"], unique=False)
    op.create_table(
        "photos",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("url", sa.String(length=1000), nullable=False),
        sa.Column("thumbnail_url", sa.String(length=1000), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("is_profile_photo", sa.Boolean(), nullable=False),
        sa.Column(
            "verification_status",
            sa.Enum(
                "UNVERIFIED",
                "PENDING",
                "VERIFIED",
                "REJECTED",
                name="photoverificationstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "visibility",
            sa.Enum("PUBLIC", "PRIVATE", name="photovisibility", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("mime_type", sa.String(length=50), nullable=True),
        sa.Column("file_size", sa.Integer(), nullable=True),
        sa.Column("uploaded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_photos_user_id_users"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_photos")),
    )
    op.create_index(op.f("ix_photos_deleted_at"), "photos", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_photos_user_id"), "photos", ["user_id"], unique=False)
    op.create_index("ix_photos_user_position", "photos", ["user_id", "position"], unique=False)
    op.create_index(op.f("ix_photos_verification_status"), "photos", ["verification_status"], unique=False)
    op.create_table(
        "profile_shares",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_user_id", sa.Uuid(), nullable=False),
        sa.Column("shared_with_user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "permission",
            sa.Enum("VIEW", "CONTACT", "MANAGE", name="sharepermission", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_user_id"], ["users.id"], name=op.f("fk_profile_shares_owner_user_id_users"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["shared_with_user_id"],
            ["users.id"],
            name=op.f("fk_profile_shares_shared_with_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_profile_shares")),
        sa.UniqueConstraint("owner_user_id", "shared_with_user_id", name="uq_profile_share"),
    )
    op.create_index(op.f("ix_profile_shares_expires_at"), "profile_shares", ["expires_at"], unique=False)
    op.create_index("ix_profile_shares_owner", "profile_shares", ["owner_user_id"], unique=False)
    op.create_index("ix_profile_shares_shared_with", "profile_shares", ["shared_with_user_id"], unique=False)
    op.create_table(
        "profiles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=True),
        sa.Column("last_name", sa.String(length=100), nullable=True),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column(
            "gender", sa.Enum("MALE", "FEMALE", "OTHER", name="gender", native_enum=False, length=32), nullable=True
        ),
        sa.Column("bio", sa.String(length=1000), nullable=True),
        sa.Column(
            "intent",
            sa.Enum("MARRIAGE", "FRIENDSHIP", "DATE", "NOT_SURE", name="intent", native_enum=False, length=32),
            nullable=True,
        ),
        sa.Column(
            "marital_status",
            sa.Enum(
                "NEVER_MARRIED",
                "DIVORCED",
                "WIDOWED",
                "AWAITING_DIVORCE",
                name="maritalstatus",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("height_cm", sa.Integer(), nullable=True),
        sa.Column(
            "body_type",
            sa.Enum("SLIM", "AVERAGE", "ATHLETIC", "HEAVY", name="bodytype", native_enum=False, length=32),
            nullable=True,
        ),
        sa.Column(
            "complexion",
            sa.Enum(
                "VERY_FAIR",
                "FAIR",
                "WHEATISH",
                "MIDDLE_BROWN",
                "DARK",
                name="complexion",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column(
            "physical_status",
            sa.Enum("NORMAL", "PHYSICALLY_CHALLENGED", name="physicalstatus", native_enum=False, length=32),
            nullable=True,
        ),
        sa.Column(
            "diet",
            sa.Enum(
                "VEGETARIAN",
                "NON_VEGETARIAN",
                "EGGITARIAN",
                "JAIN",
                "VEGAN",
                name="diet",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column(
            "drinking",
            sa.Enum(
                "NEVER",
                "OCCASIONALLY",
                "REGULARLY",
                "PREFER_NOT_TO_SAY",
                name="drinking",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column(
            "smoking",
            sa.Enum(
                "NEVER", "OCCASIONALLY", "REGULARLY", "PREFER_NOT_TO_SAY", name="smoking", native_enum=False, length=32
            ),
            nullable=True,
        ),
        sa.Column("mother_tongue", sa.String(length=50), nullable=True),
        sa.Column("preferred_language", sa.String(length=50), nullable=True),
        sa.Column("religion", sa.String(length=50), nullable=True),
        sa.Column("caste", sa.String(length=50), nullable=True),
        sa.Column("sub_caste", sa.String(length=50), nullable=True),
        sa.Column("education", sa.String(length=100), nullable=True),
        sa.Column("college", sa.String(length=150), nullable=True),
        sa.Column("field_of_study", sa.String(length=100), nullable=True),
        sa.Column("graduation_year", sa.Integer(), nullable=True),
        sa.Column(
            "employment_status",
            sa.Enum(
                "EMPLOYED",
                "SELF_EMPLOYED",
                "BUSINESS_OWNER",
                "STUDENT",
                "NOT_WORKING",
                "RETIRED",
                "HOMEMAKER",
                name="employmentstatus",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("occupation", sa.String(length=100), nullable=True),
        sa.Column("job_title", sa.String(length=100), nullable=True),
        sa.Column("workplace", sa.String(length=150), nullable=True),
        sa.Column("industry", sa.String(length=100), nullable=True),
        sa.Column("annual_income", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("income_currency", sa.String(length=3), nullable=True),
        sa.Column("country", sa.String(length=100), nullable=True),
        sa.Column("state", sa.String(length=100), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("hometown", sa.String(length=150), nullable=True),
        sa.Column("location_lat", sa.Float(), nullable=True),
        sa.Column("location_lng", sa.Float(), nullable=True),
        sa.Column("location_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "profile_created_by",
            sa.Enum(
                "SELF",
                "PARENT",
                "GUARDIAN",
                "RELATIVE",
                "FRIEND",
                "PROFILE_SERVICE",
                name="profilecreatedby",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "height_cm IS NULL OR (height_cm BETWEEN 90 AND 250)", name=op.f("ck_profiles_height_range")
        ),
        sa.CheckConstraint(
            "location_lat IS NULL OR (location_lat BETWEEN -90 AND 90)", name=op.f("ck_profiles_lat_range")
        ),
        sa.CheckConstraint(
            "location_lng IS NULL OR (location_lng BETWEEN -180 AND 180)", name=op.f("ck_profiles_lng_range")
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_profiles_user_id_users"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_profiles")),
    )
    op.create_index(op.f("ix_profiles_caste"), "profiles", ["caste"], unique=False)
    op.create_index(op.f("ix_profiles_city"), "profiles", ["city"], unique=False)
    op.create_index(op.f("ix_profiles_country"), "profiles", ["country"], unique=False)
    op.create_index(op.f("ix_profiles_date_of_birth"), "profiles", ["date_of_birth"], unique=False)
    op.create_index("ix_profiles_discovery", "profiles", ["gender", "country", "city"], unique=False)
    op.create_index(op.f("ix_profiles_gender"), "profiles", ["gender"], unique=False)
    op.create_index(op.f("ix_profiles_intent"), "profiles", ["intent"], unique=False)
    op.create_index(op.f("ix_profiles_marital_status"), "profiles", ["marital_status"], unique=False)
    op.create_index(op.f("ix_profiles_mother_tongue"), "profiles", ["mother_tongue"], unique=False)
    op.create_index(op.f("ix_profiles_occupation"), "profiles", ["occupation"], unique=False)
    op.create_index(op.f("ix_profiles_religion"), "profiles", ["religion"], unique=False)
    op.create_index(op.f("ix_profiles_state"), "profiles", ["state"], unique=False)
    op.create_index(op.f("ix_profiles_user_id"), "profiles", ["user_id"], unique=True)
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("jti", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("replaced_by_jti", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_refresh_tokens_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
    )
    op.create_index(op.f("ix_refresh_tokens_expires_at"), "refresh_tokens", ["expires_at"], unique=False)
    op.create_index(op.f("ix_refresh_tokens_jti"), "refresh_tokens", ["jti"], unique=True)
    op.create_index(op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False)
    op.create_table(
        "reports",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("reporter_id", sa.Uuid(), nullable=False),
        sa.Column("reported_user_id", sa.Uuid(), nullable=False),
        sa.Column("reason", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("reviewed_by", sa.Uuid(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["reported_user_id"], ["users.id"], name=op.f("fk_reports_reported_user_id_users"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["reporter_id"], ["users.id"], name=op.f("fk_reports_reporter_id_users"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"], ["users.id"], name=op.f("fk_reports_reviewed_by_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reports")),
    )
    op.create_index(op.f("ix_reports_reported_user_id"), "reports", ["reported_user_id"], unique=False)
    op.create_index(op.f("ix_reports_reporter_id"), "reports", ["reporter_id"], unique=False)
    op.create_index(op.f("ix_reports_status"), "reports", ["status"], unique=False)
    op.create_table(
        "subscriptions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "TRIAL",
                "ACTIVE",
                "PAST_DUE",
                "CANCELED",
                "EXPIRED",
                name="subscriptionstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("auto_renew", sa.Boolean(), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("provider_subscription_id", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "expires_at IS NULL OR expires_at >= starts_at", name=op.f("ck_subscriptions_ck_subscription_range")
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["subscription_plans.id"],
            name=op.f("fk_subscriptions_plan_id_subscription_plans"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_subscriptions_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscriptions")),
    )
    op.create_index(op.f("ix_subscriptions_expires_at"), "subscriptions", ["expires_at"], unique=False)
    op.create_index(
        op.f("ix_subscriptions_provider_subscription_id"), "subscriptions", ["provider_subscription_id"], unique=False
    )
    op.create_index(op.f("ix_subscriptions_status"), "subscriptions", ["status"], unique=False)
    op.create_index(op.f("ix_subscriptions_user_id"), "subscriptions", ["user_id"], unique=False)
    op.create_index("ix_subscriptions_user_status", "subscriptions", ["user_id", "status"], unique=False)
    op.create_table(
        "swipes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("from_user_id", sa.Uuid(), nullable=False),
        sa.Column("to_user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "action",
            sa.Enum("LIKE", "PASS", "SUPER_LIKE", name="swipeaction", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["from_user_id"], ["users.id"], name=op.f("fk_swipes_from_user_id_users"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["to_user_id"], ["users.id"], name=op.f("fk_swipes_to_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_swipes")),
        sa.UniqueConstraint("from_user_id", "to_user_id", "action", name="uq_swipe_active_unique"),
    )
    op.create_index("ix_swipes_from_created", "swipes", ["from_user_id", "created_at"], unique=False)
    op.create_index(op.f("ix_swipes_from_user_id"), "swipes", ["from_user_id"], unique=False)
    op.create_index("ix_swipes_to_from", "swipes", ["to_user_id", "from_user_id"], unique=False)
    op.create_index(op.f("ix_swipes_to_user_id"), "swipes", ["to_user_id"], unique=False)
    op.create_table(
        "user_interests",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("interest_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["interest_id"], ["interests.id"], name=op.f("fk_user_interests_interest_id_interests"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_interests_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_interests")),
        sa.UniqueConstraint("user_id", "interest_id", name="uq_user_interest"),
    )
    op.create_index(op.f("ix_user_interests_user_id"), "user_interests", ["user_id"], unique=False)
    op.create_table(
        "user_languages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("language_id", sa.Uuid(), nullable=False),
        sa.Column("is_native", sa.Boolean(), nullable=False),
        sa.Column("proficiency", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ["language_id"], ["languages.id"], name=op.f("fk_user_languages_language_id_languages"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_languages_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_languages")),
        sa.UniqueConstraint("user_id", "language_id", name="uq_user_language"),
    )
    op.create_index(op.f("ix_user_languages_user_id"), "user_languages", ["user_id"], unique=False)
    op.create_table(
        "user_privacy_settings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("show_online_status", sa.Boolean(), nullable=False),
        sa.Column("show_distance", sa.Boolean(), nullable=False),
        sa.Column("show_last_seen", sa.Boolean(), nullable=False),
        sa.Column("profile_visibility", sa.String(length=20), nullable=False),
        sa.Column("photo_visibility", sa.String(length=20), nullable=False),
        sa.Column("phone_visibility", sa.String(length=20), nullable=False),
        sa.Column("email_visibility", sa.String(length=20), nullable=False),
        sa.Column("allow_messages_from", sa.String(length=20), nullable=False),
        sa.Column("allow_match_requests", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_privacy_settings_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_privacy_settings")),
    )
    op.create_index(op.f("ix_user_privacy_settings_user_id"), "user_privacy_settings", ["user_id"], unique=True)
    op.create_table(
        "job_verifications",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "employment_type",
            sa.Enum("LOCAL", "NRI", name="employmenttype", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("employer_name", sa.String(length=200), nullable=False),
        sa.Column("job_title", sa.String(length=150), nullable=True),
        sa.Column("country", sa.String(length=100), nullable=True),
        sa.Column(
            "verification_status",
            sa.Enum(
                "PENDING_PAYMENT",
                "UNDER_REVIEW",
                "VERIFIED",
                "REJECTED",
                "EXPIRED",
                name="jobverificationstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("amount_paid", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("payment_id", sa.Uuid(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewer_id", sa.Uuid(), nullable=True),
        sa.Column("rejection_reason", sa.String(length=1000), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "expires_at IS NULL OR verified_at IS NULL OR expires_at >= verified_at",
            name=op.f("ck_job_verifications_ck_job_expiry"),
        ),
        sa.ForeignKeyConstraint(
            ["payment_id"], ["payments.id"], name=op.f("fk_job_verifications_payment_id_payments"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_id"], ["users.id"], name=op.f("fk_job_verifications_reviewer_id_users"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_job_verifications_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_verifications")),
    )
    op.create_index(op.f("ix_job_verifications_expires_at"), "job_verifications", ["expires_at"], unique=False)
    op.create_index("ix_job_verifications_status", "job_verifications", ["verification_status"], unique=False)
    op.create_index(op.f("ix_job_verifications_user_id"), "job_verifications", ["user_id"], unique=False)
    op.create_index(
        op.f("ix_job_verifications_verification_status"), "job_verifications", ["verification_status"], unique=False
    )
    op.create_table(
        "preferred_castes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("preference_id", sa.Uuid(), nullable=False),
        sa.Column("caste", sa.String(), nullable=False),
        sa.Column(
            "level",
            sa.Enum("REQUIRED", "PREFERRED", "NO_PREFERENCE", name="preferencelevel", native_enum=False, length=32),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["preference_id"],
            ["partner_preferences.id"],
            name=op.f("fk_preferred_castes_preference_id_partner_preferences"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_preferred_castes")),
        sa.UniqueConstraint("preference_id", "caste", name="uq_pref_caste"),
    )
    op.create_index(op.f("ix_preferred_castes_preference_id"), "preferred_castes", ["preference_id"], unique=False)
    op.create_table(
        "preferred_countries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("preference_id", sa.Uuid(), nullable=False),
        sa.Column("country", sa.String(), nullable=False),
        sa.Column(
            "level",
            sa.Enum("REQUIRED", "PREFERRED", "NO_PREFERENCE", name="preferencelevel", native_enum=False, length=32),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["preference_id"],
            ["partner_preferences.id"],
            name=op.f("fk_preferred_countries_preference_id_partner_preferences"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_preferred_countries")),
        sa.UniqueConstraint("preference_id", "country", name="uq_pref_country"),
    )
    op.create_index(
        op.f("ix_preferred_countries_preference_id"), "preferred_countries", ["preference_id"], unique=False
    )
    op.create_table(
        "preferred_diets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("preference_id", sa.Uuid(), nullable=False),
        sa.Column("diet", sa.String(), nullable=False),
        sa.Column(
            "level",
            sa.Enum("REQUIRED", "PREFERRED", "NO_PREFERENCE", name="preferencelevel", native_enum=False, length=32),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["preference_id"],
            ["partner_preferences.id"],
            name=op.f("fk_preferred_diets_preference_id_partner_preferences"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_preferred_diets")),
        sa.UniqueConstraint("preference_id", "diet", name="uq_pref_diet"),
    )
    op.create_index(op.f("ix_preferred_diets_preference_id"), "preferred_diets", ["preference_id"], unique=False)
    op.create_table(
        "preferred_languages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("preference_id", sa.Uuid(), nullable=False),
        sa.Column("language", sa.String(), nullable=False),
        sa.Column(
            "level",
            sa.Enum("REQUIRED", "PREFERRED", "NO_PREFERENCE", name="preferencelevel", native_enum=False, length=32),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["preference_id"],
            ["partner_preferences.id"],
            name=op.f("fk_preferred_languages_preference_id_partner_preferences"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_preferred_languages")),
        sa.UniqueConstraint("preference_id", "language", name="uq_pref_language"),
    )
    op.create_index(
        op.f("ix_preferred_languages_preference_id"), "preferred_languages", ["preference_id"], unique=False
    )
    op.create_table(
        "preferred_religions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("preference_id", sa.Uuid(), nullable=False),
        sa.Column("religion", sa.String(), nullable=False),
        sa.Column(
            "level",
            sa.Enum("REQUIRED", "PREFERRED", "NO_PREFERENCE", name="preferencelevel", native_enum=False, length=32),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["preference_id"],
            ["partner_preferences.id"],
            name=op.f("fk_preferred_religions_preference_id_partner_preferences"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_preferred_religions")),
        sa.UniqueConstraint("preference_id", "religion", name="uq_pref_religion"),
    )
    op.create_index(
        op.f("ix_preferred_religions_preference_id"), "preferred_religions", ["preference_id"], unique=False
    )
    op.create_table(
        "preferred_states",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("preference_id", sa.Uuid(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column(
            "level",
            sa.Enum("REQUIRED", "PREFERRED", "NO_PREFERENCE", name="preferencelevel", native_enum=False, length=32),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["preference_id"],
            ["partner_preferences.id"],
            name=op.f("fk_preferred_states_preference_id_partner_preferences"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_preferred_states")),
        sa.UniqueConstraint("preference_id", "state", name="uq_pref_state"),
    )
    op.create_index(op.f("ix_preferred_states_preference_id"), "preferred_states", ["preference_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_preferred_states_preference_id"), table_name="preferred_states")
    op.drop_table("preferred_states")
    op.drop_index(op.f("ix_preferred_religions_preference_id"), table_name="preferred_religions")
    op.drop_table("preferred_religions")
    op.drop_index(op.f("ix_preferred_languages_preference_id"), table_name="preferred_languages")
    op.drop_table("preferred_languages")
    op.drop_index(op.f("ix_preferred_diets_preference_id"), table_name="preferred_diets")
    op.drop_table("preferred_diets")
    op.drop_index(op.f("ix_preferred_countries_preference_id"), table_name="preferred_countries")
    op.drop_table("preferred_countries")
    op.drop_index(op.f("ix_preferred_castes_preference_id"), table_name="preferred_castes")
    op.drop_table("preferred_castes")
    op.drop_index(op.f("ix_job_verifications_verification_status"), table_name="job_verifications")
    op.drop_index(op.f("ix_job_verifications_user_id"), table_name="job_verifications")
    op.drop_index("ix_job_verifications_status", table_name="job_verifications")
    op.drop_index(op.f("ix_job_verifications_expires_at"), table_name="job_verifications")
    op.drop_table("job_verifications")
    op.drop_index(op.f("ix_user_privacy_settings_user_id"), table_name="user_privacy_settings")
    op.drop_table("user_privacy_settings")
    op.drop_index(op.f("ix_user_languages_user_id"), table_name="user_languages")
    op.drop_table("user_languages")
    op.drop_index(op.f("ix_user_interests_user_id"), table_name="user_interests")
    op.drop_table("user_interests")
    op.drop_index(op.f("ix_swipes_to_user_id"), table_name="swipes")
    op.drop_index("ix_swipes_to_from", table_name="swipes")
    op.drop_index(op.f("ix_swipes_from_user_id"), table_name="swipes")
    op.drop_index("ix_swipes_from_created", table_name="swipes")
    op.drop_table("swipes")
    op.drop_index("ix_subscriptions_user_status", table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_user_id"), table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_status"), table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_provider_subscription_id"), table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_expires_at"), table_name="subscriptions")
    op.drop_table("subscriptions")
    op.drop_index(op.f("ix_reports_status"), table_name="reports")
    op.drop_index(op.f("ix_reports_reporter_id"), table_name="reports")
    op.drop_index(op.f("ix_reports_reported_user_id"), table_name="reports")
    op.drop_table("reports")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_jti"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_expires_at"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index(op.f("ix_profiles_user_id"), table_name="profiles")
    op.drop_index(op.f("ix_profiles_state"), table_name="profiles")
    op.drop_index(op.f("ix_profiles_religion"), table_name="profiles")
    op.drop_index(op.f("ix_profiles_occupation"), table_name="profiles")
    op.drop_index(op.f("ix_profiles_mother_tongue"), table_name="profiles")
    op.drop_index(op.f("ix_profiles_marital_status"), table_name="profiles")
    op.drop_index(op.f("ix_profiles_intent"), table_name="profiles")
    op.drop_index(op.f("ix_profiles_gender"), table_name="profiles")
    op.drop_index("ix_profiles_discovery", table_name="profiles")
    op.drop_index(op.f("ix_profiles_date_of_birth"), table_name="profiles")
    op.drop_index(op.f("ix_profiles_country"), table_name="profiles")
    op.drop_index(op.f("ix_profiles_city"), table_name="profiles")
    op.drop_index(op.f("ix_profiles_caste"), table_name="profiles")
    op.drop_table("profiles")
    op.drop_index("ix_profile_shares_shared_with", table_name="profile_shares")
    op.drop_index("ix_profile_shares_owner", table_name="profile_shares")
    op.drop_index(op.f("ix_profile_shares_expires_at"), table_name="profile_shares")
    op.drop_table("profile_shares")
    op.drop_index(op.f("ix_photos_verification_status"), table_name="photos")
    op.drop_index("ix_photos_user_position", table_name="photos")
    op.drop_index(op.f("ix_photos_user_id"), table_name="photos")
    op.drop_index(op.f("ix_photos_deleted_at"), table_name="photos")
    op.drop_table("photos")
    op.drop_index(op.f("ix_payments_user_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_status"), table_name="payments")
    op.drop_index(op.f("ix_payments_provider_payment_id"), table_name="payments")
    op.drop_table("payments")
    op.drop_index(op.f("ix_partner_preferences_user_id"), table_name="partner_preferences")
    op.drop_index("ix_partner_preferences_user", table_name="partner_preferences")
    op.drop_table("partner_preferences")
    op.drop_index("ix_notifications_user_read", table_name="notifications")
    op.drop_index(op.f("ix_notifications_user_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_type"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_is_read"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_created_at"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(op.f("ix_messages_sender_id"), table_name="messages")
    op.drop_index(op.f("ix_messages_deleted_at"), table_name="messages")
    op.drop_index(op.f("ix_messages_conversation_id"), table_name="messages")
    op.drop_index("ix_messages_conversation_created", table_name="messages")
    op.drop_table("messages")
    op.drop_index("ix_matches_user_status", table_name="matches")
    op.drop_index("ix_matches_user2_status", table_name="matches")
    op.drop_index(op.f("ix_matches_user2_id"), table_name="matches")
    op.drop_index(op.f("ix_matches_user1_id"), table_name="matches")
    op.drop_index(op.f("ix_matches_status"), table_name="matches")
    op.drop_table("matches")
    op.drop_index(op.f("ix_family_members_user_id"), table_name="family_members")
    op.drop_table("family_members")
    op.drop_index(op.f("ix_families_user_id"), table_name="families")
    op.drop_table("families")
    op.drop_index(op.f("ix_conversation_participants_user_id"), table_name="conversation_participants")
    op.drop_index(op.f("ix_conversation_participants_conversation_id"), table_name="conversation_participants")
    op.drop_table("conversation_participants")
    op.drop_index(op.f("ix_blocks_blocker_id"), table_name="blocks")
    op.drop_index(op.f("ix_blocks_blocked_id"), table_name="blocks")
    op.drop_table("blocks")
    op.drop_index(op.f("ix_audit_logs_entity_type"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_entity_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_created_at"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_index("ix_audit_actor_created", table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_astrology_profiles_user_id"), table_name="astrology_profiles")
    op.drop_index(op.f("ix_astrology_profiles_rashi"), table_name="astrology_profiles")
    op.drop_table("astrology_profiles")
    op.drop_index(op.f("ix_users_role"), table_name="users")
    op.drop_index(op.f("ix_users_last_active_at"), table_name="users")
    op.drop_index(op.f("ix_users_deleted_at"), table_name="users")
    op.drop_index("ix_users_active", table_name="users")
    op.drop_index(op.f("ix_users_account_status"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_subscription_plans_is_active"), table_name="subscription_plans")
    op.drop_table("subscription_plans")
    op.drop_index(op.f("ix_states_country_code"), table_name="states")
    op.drop_table("states")
    op.drop_index(op.f("ix_religions_name"), table_name="religions")
    op.drop_table("religions")
    op.drop_index(op.f("ix_occupations_name"), table_name="occupations")
    op.drop_table("occupations")
    op.drop_index(op.f("ix_languages_code"), table_name="languages")
    op.drop_table("languages")
    op.drop_index(op.f("ix_interests_slug"), table_name="interests")
    op.drop_table("interests")
    op.drop_index(op.f("ix_education_levels_name"), table_name="education_levels")
    op.drop_table("education_levels")
    op.drop_index(op.f("ix_countries_code"), table_name="countries")
    op.drop_table("countries")
    op.drop_index(op.f("ix_conversations_last_message_at"), table_name="conversations")
    op.drop_table("conversations")
    op.drop_index(op.f("ix_castes_religion"), table_name="castes")
    op.drop_table("castes")
    op.drop_index(op.f("ix_app_config_key"), table_name="app_config")
    op.drop_table("app_config")
    # ### end Alembic commands ###
